#include "cheeter/config.h"
#include "cheeter/log.h"
#include <glib.h>
#include <stdio.h>

// Default config file template with comments
static const char *DEFAULT_CONFIG_TEMPLATE =
    "# Cheeter Configuration File\n"
    "# --------------------------\n"
    "# This file is automatically generated on first run.\n"
    "# Edit the values below to customize Cheeter's behavior.\n"
    "#\n"
    "# Lines starting with # are comments and are ignored.\n"
    "# Format: key = value\n"
    "\n"
    "[General]\n"
    "\n"
    "# hotkey - The global keyboard shortcut to toggle the cheat sheet "
    "overlay.\n"
    "#\n"
    "# Format: Modifier+Modifier+Key\n"
    "# Modifiers: Super, Ctrl, Alt, Shift (case-insensitive)\n"
    "# Key: Lowercase X11 keysym name (e.g., slash, h, space, F1)\n"
    "#\n"
    "# Examples:\n"
    "#   Super+slash      (Super + / key)\n"
    "#   Ctrl+Alt+h       (Ctrl + Alt + H key)\n"
    "#   Super+F1         (Super + F1 key)\n"
    "#\n"
    "hotkey = Super+slash\n"
    "\n"
    "# sheets_dir - Directory containing cheat sheet PDF files.\n"
    "#\n"
    "# If not set, defaults to ~/.local/share/cheeter/sheets\n"
    "# Use an absolute path. Environment variables are NOT expanded.\n"
    "#\n"
    "# Example:\n"
    "#   sheets_dir = /home/user/Documents/cheatsheets\n"
    "#\n"
    "# sheets_dir =\n"
    "\n"
    "# debug_log - Enable verbose debug logging.\n"
    "#\n"
    "# Set to true for troubleshooting. Logs are printed to stderr.\n"
    "# Values: true, false\n"
    "#\n"
    "debug_log = false\n";

// Write default config file if it doesn't exist
static void write_default_config(const char *path) {
  // Check if file already exists
  if (g_file_test(path, G_FILE_TEST_EXISTS)) {
    return;
  }

  // Ensure parent directory exists
  char *dir = g_path_get_dirname(path);
  g_mkdir_with_parents(dir, 0755);
  g_free(dir);

  // Write default config
  GError *error = NULL;
  if (!g_file_set_contents(path, DEFAULT_CONFIG_TEMPLATE, -1, &error)) {
    LOG_WARN("Could not write default config to %s: %s", path, error->message);
    g_error_free(error);
    return;
  }

  LOG_INFO("Created default config file: %s", path);
}

CheeterConfig *cheeter_config_load(const char *path) {
  CheeterConfig *config = g_new0(CheeterConfig, 1);
  GKeyFile *keyfile = g_key_file_new();
  GError *error = NULL;

  // Set defaults
  config->hotkey = g_strdup("Super+slash");
  config->sheets_dir = NULL; // NULL means use default
  config->debug_log = false;

  if (!path) {
    g_key_file_free(keyfile);
    return config;
  }

  // Create default config if it doesn't exist
  write_default_config(path);

  if (!g_key_file_load_from_file(keyfile, path, G_KEY_FILE_NONE, &error)) {
    LOG_WARN("Could not load config file %s: %s", path, error->message);
    g_error_free(error);
    g_key_file_free(keyfile);
    return config;
  }

  gchar *val_str;

  val_str = g_key_file_get_string(keyfile, "General", "hotkey", NULL);
  if (val_str) {
    g_free(config->hotkey);
    config->hotkey = val_str;
  }

  val_str = g_key_file_get_string(keyfile, "General", "sheets_dir", NULL);
  if (val_str && val_str[0] != '\0') {
    config->sheets_dir = val_str;
  } else {
    g_free(val_str);
  }

  if (g_key_file_has_key(keyfile, "General", "debug_log", NULL)) {
    config->debug_log =
        g_key_file_get_boolean(keyfile, "General", "debug_log", NULL);
  }

  g_key_file_free(keyfile);
  return config;
}

void cheeter_config_free(CheeterConfig *config) {
  if (!config)
    return;
  g_free(config->hotkey);
  g_free(config->sheets_dir);
  g_free(config);
}
